apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template.docs.fullname" . }}
  labels:
    {{- include "template.docs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.docs.replicaCount }}
  selector:
    matchLabels:
      {{- include "template.docs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "template.docs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.docs.image.repository }}:{{ .Values.docs.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.docs.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.docs.container.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.docs.container.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.docs.container.port }}
          resources:
            {{- toYaml .Values.docs.resources | nindent 12 }}
