apiVersion: v2
name: dso-doc
description: A Helm chart to deploy ...
type: application
keywords: []
home: https://github.com/cloud-pi-native/documentation
sources:
  - https://github.com/cloud-pi-native/documentation
dependencies: []
maintainers:
  - name: Team Socle
    url: https://github.com/orgs/cloud-pi-native/teams/socle
  - name: Service Team
    url: https://github.com/orgs/cloud-pi-native/teams/service-team
# icon: A URL to an SVG or PNG image to be used as an icon (optional).
deprecated: false
annotations: {}
version: 1.0.0
appVersion: 6.0.0 # x-release-please-version
