imagePullSecrets:
  - name: registry-pull-secret

docs:
  replicaCount: 1
  image:
    repository: harbor.dso.cpin.numerique-interieur.fr/documentationcpin/dso-documentation
    pullPolicy: Always
    tag: ci-cpin-hosting
  container:
    port: 8080
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    hosts:
      - host: doc-dso.app.cpin.numerique-interieur.fr
        paths:
          - path: /
            pathType: Prefix
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
