nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

docs:
  replicaCount: 1
  image:
    repository: harbor.dso.cpin.numerique-interieur.fr/documentationcpin/dso-documentation
    pullPolicy: Always
    tag: ""
  container:
    port: 8080
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
      - host: example.domain.com
        paths:
          - path: /
            pathType: Prefix
    tls: []
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
